name: Validate pull request

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  Helm_chart_Tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/helm-chart-tests

  Build_Alpine:
    runs-on: ubuntu-latest
    needs:
      - Helm_chart_Tests
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Buildkit setup
      - uses: ./.github/actions/buildx-setup

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          #key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Fix issue with building Alpine # See https://gitlab.alpinelinux.org/alpine/aports/-/issues/12406
        run: |
          update-binfmts --enable

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: |
            boky/redis-cluster-proxy-docker:latest
            boky/redis-cluster-proxy-docker:latest-alpine
          platforms: "linux/s390x,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le"
          cache-from: type=local,src=/tmp/.buildx-cache/alpine
          #build-args: |
          #  BASE_IMAGE=alpine:latest

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

